---
- name: deploy newest version of api
  hosts: vps
  become: yes

  tasks:

    - name: add github to known hosts
      ansible.builtin.known_hosts:
          name: github.com
          key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
          path: /root/.ssh/known_hosts   
          state: present

    - name: pull latest changes
      git:
        repo: git@github.com:shikajiko/netics-oprec-module1-2026.git
        dest: "{{ app_path }}"
        version: main
        accept_hostkey: yes
        key_file: /home/riyanfadli/.ssh/id_ed25519
      become_user: riyanfadli  

    - name: build docker image
      command: docker build -t node-api .
      args:
        chdir: "{{ app_path }}"

    - name: run docker container
      community.docker.docker_container:
        name: node-api
        image: node-api
        state: started
        restart_policy: always
        ports:
        - "3000:3000"
    
    - name: install nginx
      apt: 
        name: nginx
        state: latest
        update_cache: yes

    - name: remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: add nginx config
      copy:
        src: /home/riyan/oprec-netics-2026/netics-oprec-module1-2026/src/nginx/health-api
        dest: /etc/nginx/sites-available
        owner: root       
        group: root
        mode: '0644'
      
    - name: enable web
      file: 
        src: /etc/nginx/sites-available/health-api
        dest: /etc/nginx/sites-enabled/health-api
        state: link

    - name: check if nginx is running
      systemd:
        name: nginx
        enabled: yes
        state: started

  vars:
    user: "riyanfadli"
    app_path: "/home/riyanfadli/netics-oprec-module1-2026/src/app"
